apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-svc
  name: api-svc
  namespace: test
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: api
  type: ClusterIP
